[package]
name = "js_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utf8_slice = "1.0.0"
regex = "1.5.5"
lazy_static = "1.4.0"